import type { SCAEvent } from '@/types'

/* The committed event list. Used when Google Calendar sync is not
 * configured or the fetch fails, so the page always has something real to
 * show. Once sync is live this is a safety net, not the source of truth:
 * edit the Google Calendar, not this file. */
export const FALLBACK_EVENTS: SCAEvent[] = [
  {
    id: 'placements-interns-panel-oct-2026',
    title: 'Placements and Interns Panel',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-02T13:00:00'),
    endDate: new Date('2026-10-02T14:30:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'PANEL',
    poster: null,
  },
  {
    id: 'placements-interns-roundtable-oct-2026',
    title: 'Placements and Interns Roundtable',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-12T15:00:00'),
    endDate: new Date('2026-10-12T16:30:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'PANEL',
    poster: null,
  },
  {
    id: 'career-panel-oct-2026',
    title: 'Career Panel',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-15T12:00:00'),
    endDate: new Date('2026-10-15T13:30:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'PANEL',
    poster: null,
  },
  {
    id: 'capture-the-flag-oct-2026',
    title: 'Capture the Flag',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-23T10:00:00'),
    endDate: new Date('2026-10-23T16:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'HACKATHON',
    poster: null,
  },
  {
    id: 'fireside-chat-harris-khaliq-oct-2026',
    title: 'Fireside Chat with Cllr. Harris Khaliq',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-26T17:00:00'),
    endDate: new Date('2026-10-26T18:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'TALK',
    poster: null,
  },
  {
    id: 'fireside-chat-hamza-hanif-oct-2026',
    title: 'Fireside Chat with Hamza Hanif, Founder and CEO of Sunna Supplements',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-29T17:30:00'),
    endDate: new Date('2026-10-29T18:30:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'TALK',
    poster: null,
  },
  {
    id: 'scratch-hackathon-nov-2026',
    title: 'Scratch Hackathon',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-11-06T11:00:00'),
    endDate: new Date('2026-11-06T18:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'HACKATHON',
    poster: null,
  },
  {
    id: 'build-your-own-llm-2026-10-07',
    title: 'Build Your Own LLM',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-07T15:00:00'),
    endDate: new Date('2026-10-07T17:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'build-your-own-llm-2026-10-14',
    title: 'Build Your Own LLM',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-14T15:00:00'),
    endDate: new Date('2026-10-14T17:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'build-your-own-llm-2026-10-21',
    title: 'Build Your Own LLM',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-21T15:00:00'),
    endDate: new Date('2026-10-21T17:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'build-your-own-llm-2026-10-28',
    title: 'Build Your Own LLM',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-28T15:00:00'),
    endDate: new Date('2026-10-28T17:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'build-your-own-llm-2026-11-04',
    title: 'Build Your Own LLM',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-11-04T15:00:00'),
    endDate: new Date('2026-11-04T17:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'build-your-own-llm-2026-11-11',
    title: 'Build Your Own LLM',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-11-11T15:00:00'),
    endDate: new Date('2026-11-11T17:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'build-your-own-llm-2026-11-18',
    title: 'Build Your Own LLM',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-11-18T15:00:00'),
    endDate: new Date('2026-11-18T17:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'build-your-own-llm-2026-11-25',
    title: 'Build Your Own LLM',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-11-25T15:00:00'),
    endDate: new Date('2026-11-25T17:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'welcome-week-sept-2026',
    title: 'Welcome Week: Meet the Committee',
    description:
      'Kick off the new academic year with the SCA. Meet the committee, win prizes, and get stuck into a week of fun activities.',
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-09-14T12:00:00'),
    endDate: null,
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'NETWORKING',
    poster: null,
  },
  {
    id: 'leetcode-club-2026-09-29',
    title: 'LeetCode Club',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-09-29T14:00:00'),
    endDate: new Date('2026-09-29T16:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'leetcode-club-2026-10-06',
    title: 'LeetCode Club',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-06T14:00:00'),
    endDate: new Date('2026-10-06T16:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'leetcode-club-2026-10-13',
    title: 'LeetCode Club',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-13T14:00:00'),
    endDate: new Date('2026-10-13T16:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'leetcode-club-2026-10-20',
    title: 'LeetCode Club',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-20T14:00:00'),
    endDate: new Date('2026-10-20T16:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'leetcode-club-2026-10-27',
    title: 'LeetCode Club',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-27T14:00:00'),
    endDate: new Date('2026-10-27T16:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'leetcode-club-2026-11-03',
    title: 'LeetCode Club',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-11-03T14:00:00'),
    endDate: new Date('2026-11-03T16:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'leetcode-club-2026-11-10',
    title: 'LeetCode Club',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-11-10T14:00:00'),
    endDate: new Date('2026-11-10T16:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'leetcode-club-2026-11-17',
    title: 'LeetCode Club',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-11-17T14:00:00'),
    endDate: new Date('2026-11-17T16:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'leetcode-club-2026-11-24',
    title: 'LeetCode Club',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-11-24T14:00:00'),
    endDate: new Date('2026-11-24T16:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'application-simulation-day-oct-2026',
    title: 'Application Simulation Day',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-10-01T09:00:00'),
    endDate: new Date('2026-10-01T17:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'OTHER',
    poster: null,
  },
  {
    id: 'social-night-june-2026',
    title: 'Social Night: Debate & Gaming',
    description:
      'A collaborative social night with BCU Gaming Society and the Law Debating & Mooting Society. Speed debates on topics from Gaming and AI (12–3 PM), then a relaxed gaming session to meet students from across courses and societies (3–8 PM).',
    location: 'STEAMhouse, CST-302',
    isOnline: false,
    date: new Date('2026-06-04T12:00:00'),
    endDate: new Date('2026-06-04T20:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'OTHER',
    poster: '/posters/social-night-june-2026.jpg',
  },
  {
    id: 'leetcode-club-session-2026-09-23',
    title: 'LeetCode Club Session',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-09-23T13:00:00'),
    endDate: new Date('2026-09-23T14:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
  {
    id: 'placements-interns-panel-cs-2026-09-23',
    title: 'Placements and Interns Panel (CS)',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-09-23T17:30:00'),
    endDate: new Date('2026-09-23T19:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'PANEL',
    poster: null,
  },
  {
    id: 'scratch-hackathon-2026-09-30',
    title: 'Scratch Hackathon',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-09-30T15:00:00'),
    endDate: new Date('2026-09-30T18:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'HACKATHON',
    poster: null,
  },
  {
    id: 'project-session-swe-2026-09-24',
    title: 'Project Session (SWE)',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: new Date('2026-09-24T13:30:00'),
    endDate: new Date('2026-09-24T15:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'WORKSHOP',
    poster: null,
  },
]
