import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const toSlug = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').substring(0, 80)

function mapType(raw: string): 'INTERNSHIP' | 'PLACEMENT' | 'GRADUATE' | 'SPRING_WEEK' | 'INSIGHT' {
  const t = raw.toLowerCase()
  if (t.includes('insight')) return 'INSIGHT'
  if (t.includes('spring week') || t.includes('spring insight')) return 'SPRING_WEEK'
  if (t.includes('placement') || t.includes('placement year') || t.includes('industrial placement')) return 'PLACEMENT'
  if (
    t.includes('graduate') || t.includes('new grad') || t.includes('grad scheme') ||
    t.includes('analyst programme') || t.includes('apprenticeship')
  ) return 'GRADUATE'
  return 'INTERNSHIP'
}

function parseDeadline(raw: string): Date | null {
  if (!raw || raw.toLowerCase() === 'rolling') return null
  // formats like "31 May 2026", "14 September 2026", "6 October 2026", "29 June 2026"
  const d = new Date(raw)
  if (!isNaN(d.getTime())) return d
  return null
}

function mapWorkMode(location: string): 'REMOTE' | 'HYBRID' | 'ONSITE' {
  const l = location.toLowerCase()
  if (l.includes('remote uk') || l === 'remote') return 'REMOTE'
  if (l.includes('remote')) return 'HYBRID'
  return 'ONSITE'
}

type Row = {
  company: string
  title: string
  type: string
  location: string
  deadline: string
  startDate: string
  applyUrl: string
  website: string
  logo: string
}

const rows: Row[] = [
  { company: 'Altera', title: 'Internship - FPGA Software Design Engineer', type: 'Software Engineering Industrial Placement', location: 'United Kingdom', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://altera.wd1.myworkdayjobs.com/en-US/Altera/job/Internship---FPGA-Software-Design-Engineer_R01412', website: 'https://www.altera.com', logo: 'https://www.google.com/s2/favicons?domain=altera.com&sz=256' },
  { company: 'Amazon', title: '2026 Applied Scientist Intern', type: 'AI/ML Internship', location: 'United Kingdom', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://www.amazon.jobs/en-gb/jobs/3182383/2026-applied-scientist-intern-amazon-university-talent-acquisition', website: 'https://www.amazon.co.uk', logo: 'https://www.google.com/s2/favicons?domain=amazon.co.uk&sz=256' },
  { company: 'Amazon', title: '2026 Data Engineering Internship - UK', type: 'Data Engineering Internship', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://www.amazon.jobs/en-gb/jobs/3183839/data-engineer-internship-uk-amazon-university-talent-acquisition-auta', website: 'https://www.amazon.co.uk', logo: 'https://www.google.com/s2/favicons?domain=amazon.co.uk&sz=256' },
  { company: 'Amazon', title: '2026 Data Scientist Internship', type: 'Data/AI/ML Internship', location: 'United Kingdom', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://www.amazon.jobs/en-gb/jobs/3125279/2026-data-scientist-internship-amazon-university-talent-acquisition', website: 'https://www.amazon.co.uk', logo: 'https://www.google.com/s2/favicons?domain=amazon.co.uk&sz=256' },
  { company: 'Amazon', title: '2026 Software Dev Engineer Intern - UK', type: 'Software Engineering Internship', location: 'London; Cambridge; Edinburgh', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://www.amazon.jobs/en-gb/jobs/3072061/2026-software-dev-engineer-intern-uk', website: 'https://www.amazon.co.uk', logo: 'https://www.google.com/s2/favicons?domain=amazon.co.uk&sz=256' },
  { company: 'Amazon', title: 'Engineering Intern', type: 'Engineering / Infrastructure Internship', location: 'London', deadline: 'Rolling', startDate: 'July 2026', applyUrl: 'https://www.amazon.jobs/en-gb/jobs/3083028/engineering-intern', website: 'https://www.amazon.co.uk', logo: 'https://www.google.com/s2/favicons?domain=amazon.co.uk&sz=256' },
  { company: 'Amazon', title: 'Security Specialist Intern, Data Centre Security', type: 'Cyber Security Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://www.amazon.jobs/en-gb/jobs/3191381/security-specialist-intern-data-centre-security', website: 'https://www.amazon.co.uk', logo: 'https://www.google.com/s2/favicons?domain=amazon.co.uk&sz=256' },
  { company: 'Amazon', title: 'Software Development Engineer - 2026', type: 'Graduate Software Engineering Programme', location: 'London; Cambridge; Edinburgh', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://www.amazon.jobs/en-gb/jobs/10408763/software-development-engineer-2026', website: 'https://www.amazon.co.uk', logo: 'https://www.google.com/s2/favicons?domain=amazon.co.uk&sz=256' },
  { company: 'Amazon', title: 'UX Design Intern, Interaction Design', type: 'Technology / Product Design Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://www.amazon.jobs/en-gb/jobs/3189014/ux-design-intern-interaction-design', website: 'https://www.amazon.co.uk', logo: 'https://www.google.com/s2/favicons?domain=amazon.co.uk&sz=256' },
  { company: 'Apple', title: 'Camera Algorithms Intern', type: 'AI / Computer Vision Internship', location: 'Cambridge', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobs.apple.com/en-gb/details/200647028-1251/camera-algorithms-intern?team=HRDWR', website: 'https://www.apple.com/uk', logo: 'https://www.google.com/s2/favicons?domain=apple.com&sz=256' },
  { company: 'Apple', title: 'Engineering Program Management Undergrad Internships', type: 'Technology / Engineering Internship', location: 'United Kingdom', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://jobs.apple.com/en-gb/details/200664330-3810/engineering-program-management-undergrad-internships', website: 'https://www.apple.com/uk', logo: 'https://www.google.com/s2/favicons?domain=apple.com&sz=256' },
  { company: 'Apple', title: 'GPU Internship - Platform Architecture', type: 'Hardware / Software Internship', location: 'Cambridge; London; St Albans', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobs.apple.com/en-gb/details/200617616-2114/gpu-internship-platform-architecture', website: 'https://www.apple.com/uk', logo: 'https://www.google.com/s2/favicons?domain=apple.com&sz=256' },
  { company: 'Apple', title: 'Hardware Undergrad Engineering Internships', type: 'Hardware Engineering Internship', location: 'United Kingdom', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://jobs.apple.com/en-gb/details/200663981-3810/hardware-undergrad-engineering-internships?team=STDNT', website: 'https://www.apple.com/uk', logo: 'https://www.google.com/s2/favicons?domain=apple.com&sz=256' },
  { company: 'Apple', title: 'Machine Learning and Artificial Intelligence Undergrad Internships', type: 'Data/AI/ML Internship', location: 'United Kingdom', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://jobs.apple.com/en-gb/details/200664780-3810/machine-learning-and-artificial-intelligence-undergrad-internships?team=STDNT', website: 'https://www.apple.com/uk', logo: 'https://www.google.com/s2/favicons?domain=apple.com&sz=256' },
  { company: 'Apple', title: 'Machine Learning Engineer - NLP/LLM (2026 New Grad)', type: 'Machine Learning Graduate / New Grad', location: 'United Kingdom', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobs.apple.com/en-gb/details/200658046-0351/machine-learning-engineer-nlp-llm-2026-new-grad?team=MLAI', website: 'https://www.apple.com/uk', logo: 'https://www.google.com/s2/favicons?domain=apple.com&sz=256' },
  { company: 'Apple', title: 'SoC Performance Modeling Internship - Platform Architecture', type: 'Hardware / Software Internship', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobs.apple.com/en-gb/details/200629965-2114/soc-performance-modeling-internship-platform-architecture', website: 'https://www.apple.com/uk', logo: 'https://www.google.com/s2/favicons?domain=apple.com&sz=256' },
  { company: 'Apple', title: 'Software Engineering Intern (Machine Learning & AI Workflows)', type: 'AI / ML Software Internship', location: 'United Kingdom', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobs.apple.com/en-gb/details/200655115-1731/software-engineering-intern-machine-learning-ai-workflows?team=HRDWR', website: 'https://www.apple.com/uk', logo: 'https://www.google.com/s2/favicons?domain=apple.com&sz=256' },
  { company: 'Apple', title: 'Software Engineering Masters Internships', type: 'Software Engineering Internship', location: 'United Kingdom', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://jobs.apple.com/en-gb/details/200664320/software-engineering-masters-internships', website: 'https://www.apple.com/uk', logo: 'https://www.google.com/s2/favicons?domain=apple.com&sz=256' },
  { company: 'Apple', title: 'Software Undergrad Engineering Internships', type: 'Software Engineering Internship', location: 'United Kingdom', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://jobs.apple.com/en-gb/details/200664785/software-undergrad-engineering-internships', website: 'https://www.apple.com/uk', logo: 'https://www.google.com/s2/favicons?domain=apple.com&sz=256' },
  { company: 'Arm', title: 'Graduate Engineer - Edge AI System Performance', type: 'AI / Software Engineering Graduate Scheme', location: 'Cambridge', deadline: 'Rolling', startDate: 'September 2026', applyUrl: 'https://careers.arm.com/job/cambridge/graduate-engineer-edge-ai-system-performance/33099/95262406992', website: 'https://www.arm.com', logo: 'https://www.google.com/s2/favicons?domain=arm.com&sz=256' },
  { company: 'Arm', title: 'Graduate Engineer - System Performance Team', type: 'Hardware / Software Graduate Scheme', location: 'Cambridge', deadline: 'Rolling', startDate: 'September 2026', applyUrl: 'https://careers.arm.com/en/job/cambridge/graduate-engineer-system-performance-team/33099/95128344880', website: 'https://www.arm.com', logo: 'https://www.google.com/s2/favicons?domain=arm.com&sz=256' },
  { company: 'AVEVA', title: 'Cloud Operations & Infrastructure Graduate', type: 'Cloud / Infrastructure Graduate Scheme', location: 'Cambridge', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://aveva.wd3.myworkdayjobs.com/en-US/AVEVA_careers/job/Cloud-Developer-Graduate_R011704', website: 'https://www.aveva.com', logo: 'https://www.google.com/s2/favicons?domain=aveva.com&sz=256' },
  { company: 'AWS', title: '2026 Data Center Technician Intern', type: 'Cloud/Infrastructure Internship', location: 'Greater London (Slough); Hemel Hempstead', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://amazon.jobs/en/jobs/3110268/2026-data-center-technician-intern', website: 'https://aws.amazon.com', logo: 'https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=256' },
  { company: 'AWS', title: 'Associate Solutions Architect Intern 2026', type: 'Cloud / Solutions Architecture Internship', location: 'London', deadline: 'Rolling', startDate: 'September 2026', applyUrl: 'https://www.amazon.jobs/en-gb/jobs/3143769/associate-solutions-architect-intern-2026', website: 'https://aws.amazon.com', logo: 'https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=256' },
  { company: 'Axon', title: '2026 UK Software Engineering Internship', type: 'Software Engineering Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://job-boards.greenhouse.io/axontalentcommunity/jobs/7122432003', website: 'https://www.axon.com', logo: 'https://www.google.com/s2/favicons?domain=axon.com&sz=256' },
  { company: 'BAE Systems', title: 'Graduate Computing and IT Engineer', type: 'Computing / IT Graduate Scheme', location: 'Frimley', deadline: 'Rolling', startDate: '2027', applyUrl: 'https://jobsearch.baesystems.com/job/graduate-computing-and-it-engineer-v05900-10384', website: 'https://www.baesystems.com/en-uk', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'BAE Systems', title: 'Graduate Data Consultant - Broad Oak', type: 'Data Graduate Scheme', location: 'Broad Oak; Portsmouth', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobsearch.baesystems.com/job/graduate-data-consultant-v05944-10401', website: 'https://www.baesystems.com', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'BAE Systems', title: 'Graduate Data Consultant - Frimley', type: 'Data Graduate Scheme', location: 'Frimley', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobsearch.baesystems.com/job/graduate-data-consultant-123034', website: 'https://www.baesystems.com', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'BAE Systems', title: 'Graduate Data Engineer - London', type: 'Data Engineering Graduate Scheme', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobsearch.baesystems.com/job/graduate-data-engineer-123012', website: 'https://www.baesystems.com', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'BAE Systems', title: 'Graduate Data Researcher', type: 'Data/AI/ML Graduate Scheme', location: 'Great Baddow; Chelmsford', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobsearch.baesystems.com/job/graduate-data-researcher-123005', website: 'https://www.baesystems.com', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'BAE Systems', title: 'Graduate Information Management & Technology', type: 'Technology Graduate Scheme', location: 'Barrow-in-Furness', deadline: 'Rolling', startDate: '2027', applyUrl: 'https://jobsearch.baesystems.com/job/graduate-information-management-technology-v05923-10395', website: 'https://www.baesystems.com/en-uk', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'BAE Systems', title: 'Graduate Network Engineer', type: 'Cloud/Infrastructure / Network Engineering Graduate Scheme', location: 'Yeovil', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobsearch.baesystems.com/job/graduate-network-engineer-v05946-10403', website: 'https://www.baesystems.com', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'BAE Systems', title: 'Graduate Security Consultant - London', type: 'Cyber Security Graduate Scheme', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobsearch.baesystems.com/job/graduate-security-consultant-123006', website: 'https://www.baesystems.com', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'BAE Systems', title: 'Graduate Software Engineer', type: 'Software Engineering Graduate Scheme', location: 'Christchurch', deadline: '12 April 2027', startDate: '12 April 2027', applyUrl: 'https://jobsearch.baesystems.com/job/graduate-software-engineer-v05928-10397', website: 'https://www.baesystems.com/en-uk', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'BAE Systems', title: 'Graduate Software Engineer - Frimley', type: 'Software Engineering Graduate Scheme', location: 'Frimley', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobsearch.baesystems.com/job/graduate-software-engineer-123033', website: 'https://www.baesystems.com', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'BAE Systems', title: 'Graduate Software Engineer - Leeds', type: 'Software Engineering Graduate Scheme', location: 'Leeds', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobsearch.baesystems.com/job/graduate-software-engineer-123013', website: 'https://www.baesystems.com', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'BAE Systems', title: 'Graduate Systems Engineer', type: 'Systems / Software Engineering Graduate Scheme', location: 'Broad Oak', deadline: '12 April 2027', startDate: '12 April 2027', applyUrl: 'https://jobsearch.baesystems.com/job/graduate-systems-engineer-v05857-10184', website: 'https://www.baesystems.com/en-uk', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'BAE Systems', title: 'National Security Cyber Accelerator', type: 'Cyber Security Programme', location: 'Gloucester; Manchester', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobsearch.baesystems.com/job/national-security-cyber-accelerator-122986', website: 'https://www.baesystems.com/en-uk', logo: 'https://www.google.com/s2/favicons?domain=baesystems.com&sz=256' },
  { company: 'Bending Spoons', title: 'Graduate AI Software Engineer', type: 'AI / Software Engineering Graduate Role', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'ASAP / 2026', applyUrl: 'https://jobs.bendingspoons.com/positions/695a6f1127aeb1bf21a1b44d/apply', website: 'https://bendingspoons.com', logo: 'https://www.google.com/s2/favicons?domain=bendingspoons.com&sz=256' },
  { company: 'Bending Spoons', title: 'Graduate Security Engineer', type: 'Cyber Security Graduate Role', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'ASAP / 2026', applyUrl: 'https://jobs.bendingspoons.com/positions/69ca9a9ff0efcb3563c31df4/apply', website: 'https://bendingspoons.com', logo: 'https://www.google.com/s2/favicons?domain=bendingspoons.com&sz=256' },
  { company: 'Capgemini', title: 'Graduate Software Engineer', type: 'Software Engineering Graduate Scheme', location: 'United Kingdom', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://www.capgemini.com/jobs/439253-en_GB%2Bsap_btp/', website: 'https://www.capgemini.com/gb-en', logo: 'https://www.google.com/s2/favicons?domain=capgemini.com&sz=256' },
  { company: 'CENSUS', title: 'Cybersecurity Engineering Internship Program: Learn. Hack. Secure!', type: 'Cyber Security Internship', location: 'United Kingdom (Remote)', deadline: 'Rolling', startDate: 'July 2026', applyUrl: 'https://census-labs.com/openings/', website: 'https://census-labs.com', logo: 'https://www.google.com/s2/favicons?domain=census-labs.com&sz=256' },
  { company: 'Cloudflare', title: 'GRC Team Intern (Summer 2026)', type: 'Cyber Security / GRC Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://job-boards.greenhouse.io/cloudflare/jobs/7577564', website: 'https://www.cloudflare.com', logo: 'https://www.google.com/s2/favicons?domain=cloudflare.com&sz=256' },
  { company: 'Cloudflare', title: 'Security Engineer Intern (Summer 2026)', type: 'Cyber Security Engineering Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://job-boards.greenhouse.io/cloudflare/jobs/7582169', website: 'https://www.cloudflare.com', logo: 'https://www.google.com/s2/favicons?domain=cloudflare.com&sz=256' },
  { company: 'Cloudflare', title: 'Technical Support Engineer Intern (Summer 2026)', type: 'Cloud/Infrastructure / Technical Support Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://job-boards.greenhouse.io/cloudflare/jobs/7726879', website: 'https://www.cloudflare.com', logo: 'https://www.google.com/s2/favicons?domain=cloudflare.com&sz=256' },
  { company: 'Dassault Systèmes', title: 'Sales Operations Intern', type: 'Technology / SaaS Operations Internship', location: 'Warwick', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://www.3ds.com/careers/jobs/sales-operations-intern-548020', website: 'https://www.3ds.com', logo: 'https://www.google.com/s2/favicons?domain=3ds.com&sz=256' },
  { company: 'Deliveroo', title: 'Software Engineer Intern', type: 'Software Engineering Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://jobs.ashbyhq.com/deliveroo/3e0440a9-7abc-45b0-8520-d3e13083d0f3', website: 'https://deliveroo.co.uk', logo: 'https://www.google.com/s2/favicons?domain=deliveroo.co.uk&sz=256' },
  { company: 'DRW', title: 'Software Developer Intern - Industrial Placement', type: 'Quant/Trading Technology Industrial Placement', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://job-boards.greenhouse.io/drwuniversityjobs/jobs/7364884', website: 'https://drw.com', logo: 'https://www.google.com/s2/favicons?domain=drw.com&sz=256' },
  { company: 'DXC Technology', title: 'DXC Graduate Programme 2026', type: 'Technology Graduate Scheme', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://dxctechnology.wd1.myworkdayjobs.com/en-US/DXCJobs/job/GBR---ENG---LONDON/DXC-Graduate-Programme-2026_51567282', website: 'https://dxc.com', logo: 'https://www.google.com/s2/favicons?domain=dxc.com&sz=256' },
  { company: 'EY', title: 'Technology Risk Summer Internship Programme 2026', type: 'Technology Risk / Cyber Security Summer Internship', location: 'United Kingdom', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://eyglobal.yello.co/jobs/r0QqKBMqclcrBs1_PGjnjw', website: 'https://www.ey.com', logo: 'https://www.google.com/s2/favicons?domain=ey.com&sz=256' },
  { company: 'Freetrade', title: 'Security Engineer Intern', type: 'Cyber Security Internship', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobs.ashbyhq.com/freetrade/f44c9df8-ec02-4fde-a75e-ad0f220147cd', website: 'https://freetrade.io', logo: 'https://www.google.com/s2/favicons?domain=freetrade.io&sz=256' },
  { company: 'G-Research', title: 'Natural Language Processing Internship', type: 'AI / NLP Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://gresearch.wd103.myworkdayjobs.com/en-US/G-Research/job/Natural-Language-Processing-Internship_R3269', website: 'https://www.gresearch.com', logo: 'https://www.google.com/s2/favicons?domain=gresearch.com&sz=256' },
  { company: 'GE Aerospace', title: 'Digital Technology - Cyber Security 12 Month Placement', type: 'Cyber Security / Digital Technology Placement Year', location: 'Cheltenham', deadline: 'Rolling', startDate: 'Summer / Autumn 2026', applyUrl: 'https://geaerospace.wd5.myworkdayjobs.com/it-IT/GE_ExternalSite/job/GE-Aerospace-Digital-Technology---12-Month-Placement_R5017590-1', website: 'https://www.geaerospace.com', logo: 'https://www.google.com/s2/favicons?domain=geaerospace.com&sz=256' },
  { company: 'Goldman Sachs', title: '2026 EMEA New Analyst Programme - Engineering', type: 'Engineering Graduate / New Analyst Programme', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://www.goldmansachs.com/careers/students/programs-and-internships/emea/new-analyst-programme', website: 'https://www.goldmansachs.com', logo: 'https://www.google.com/s2/favicons?domain=goldmansachs.com&sz=256' },
  { company: 'Goldman Sachs', title: '2026 EMEA Summer Analyst Programme - Engineering', type: 'Engineering Summer Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://www.goldmansachs.com/careers/students/programs-and-internships/emea/summer-analyst-programme', website: 'https://www.goldmansachs.com', logo: 'https://www.google.com/s2/favicons?domain=goldmansachs.com&sz=256' },
  { company: 'Goldman Sachs', title: '2026 EMEA Summer Associate Programme - Engineering and Quantitative Strategists', type: 'Engineering / Quant Summer Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://www.goldmansachs.com/careers/students/programs-and-internships/emea/summer-associate-programme', website: 'https://www.goldmansachs.com', logo: 'https://www.google.com/s2/favicons?domain=goldmansachs.com&sz=256' },
  { company: 'Graphcore', title: '2026 Graduate Firmware Engineer', type: 'Firmware Graduate Scheme', location: 'Bristol', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/graphcore/jobs/8238597002', website: 'https://www.graphcore.ai', logo: 'https://www.google.com/s2/favicons?domain=graphcore.ai&sz=256' },
  { company: 'Graphcore', title: '2026 Graduate IT Infrastructure Engineer', type: 'IT Infrastructure Graduate Scheme', location: 'Bristol', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/graphcore/jobs/8425273002', website: 'https://www.graphcore.ai', logo: 'https://www.google.com/s2/favicons?domain=graphcore.ai&sz=256' },
  { company: 'Graphcore', title: '2026 Graduate Machine Learning Engineer - Applied AI', type: 'AI / ML Graduate Scheme', location: 'Bristol', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/graphcore/jobs/8234675002', website: 'https://www.graphcore.ai', logo: 'https://www.google.com/s2/favicons?domain=graphcore.ai&sz=256' },
  { company: 'Graphcore', title: '2026 Graduate Software Engineer - AI/ML Test Systems', type: 'AI / ML Software Graduate Scheme', location: 'Bristol', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/graphcore/jobs/8245655002', website: 'https://www.graphcore.ai', logo: 'https://www.google.com/s2/favicons?domain=graphcore.ai&sz=256' },
  { company: 'Graphcore', title: '2026 Graduate Software Engineer - Analysis Tools', type: 'Software Engineering Graduate Scheme', location: 'Bristol', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/graphcore/jobs/8420657002', website: 'https://www.graphcore.ai', logo: 'https://www.google.com/s2/favicons?domain=graphcore.ai&sz=256' },
  { company: 'Graphcore', title: '2026 Graduate Software Engineer - DevOps', type: 'DevOps Graduate Scheme', location: 'Bristol', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/graphcore/jobs/8282735002', website: 'https://www.graphcore.ai', logo: 'https://www.google.com/s2/favicons?domain=graphcore.ai&sz=256' },
  { company: 'Graphcore', title: '2026 Graduate Software Engineer - Drivers', type: 'Software Engineering Graduate Scheme', location: 'Bristol', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/graphcore/jobs/8238605002', website: 'https://www.graphcore.ai', logo: 'https://www.google.com/s2/favicons?domain=graphcore.ai&sz=256' },
  { company: 'Graphcore', title: '2026 Graduate Software Engineer - ML Kernels & Runtime Team', type: 'AI / ML Software Graduate Scheme', location: 'Bristol', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/graphcore/jobs/8230202002', website: 'https://www.graphcore.ai', logo: 'https://www.google.com/s2/favicons?domain=graphcore.ai&sz=256' },
  { company: 'Graphcore', title: '2026 Graduate Software Engineer - Triton', type: 'AI / ML Software Graduate Scheme', location: 'Bristol', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/graphcore/jobs/8238577002', website: 'https://www.graphcore.ai', logo: 'https://www.google.com/s2/favicons?domain=graphcore.ai&sz=256' },
  { company: 'Graphcore', title: 'Intern - Research', type: 'AI Research Internship', location: 'Bristol; Cambridge; London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/graphcore/jobs/8287389002', website: 'https://www.graphcore.ai', logo: 'https://www.google.com/s2/favicons?domain=graphcore.ai&sz=256' },
  { company: 'Guggenheim Securities', title: '2026 Investment Banking Intern - Technology & Services', type: 'Technology & Services Summer Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://guggenheim.wd1.myworkdayjobs.com/en-US/Guggenheim_Careers_Campus/job/XMLNAME-2026-Investment-Banking-Intern---Technology---Services--London-_14631', website: 'https://www.guggenheimpartners.com', logo: 'https://www.google.com/s2/favicons?domain=guggenheimpartners.com&sz=256' },
  { company: 'HP', title: 'Graduate Software Developer (C#) - 2-year Placement', type: 'Graduate Software Placement', location: 'Cambridge', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://hp.wd5.myworkdayjobs.com/en-US/ExternalCareerSite/job/Cambridge-Cambridgeshire-United-Kingdom/Graduate-Software-Developer--C----2-year-Placement_3156191-1/apply/autofillWithResume', website: 'https://www.hp.com/gb-en', logo: 'https://www.google.com/s2/favicons?domain=hp.com&sz=256' },
  { company: 'Intropic', title: 'Quantitative Developer', type: 'Quant Developer Graduate / Early Career', location: 'London', deadline: 'Rolling', startDate: 'H1 2026', applyUrl: 'https://jobs.lever.co/intropic/e7f90e06-05e2-40d8-b9f5-df4c96792dd2', website: 'https://www.intropic.io', logo: 'https://www.google.com/s2/favicons?domain=intropic.io&sz=256' },
  { company: 'Intropic', title: 'Quantrepreneur - Engineering', type: 'Quant/Trading Technology Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://jobs.lever.co/intropic/c31c65cc-178d-4a50-bc6a-4f4b057f4381', website: 'https://intropic.io', logo: 'https://www.google.com/s2/favicons?domain=intropic.io&sz=256' },
  { company: 'Intropic', title: 'Quantrepreneur - Quantitative Developer', type: 'Quant Developer Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://jobs.lever.co/intropic/1427876a-fb80-4ee1-96da-79cac32a7803', website: 'https://www.intropic.io', logo: 'https://www.google.com/s2/favicons?domain=intropic.io&sz=256' },
  { company: 'Intropic', title: 'Quantrepreneur - Research Analyst', type: 'Quant / Trading Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://jobs.lever.co/intropic/a4a5fb03-4a97-4f18-a680-7dd5663955a2', website: 'https://www.intropic.io', logo: 'https://www.google.com/s2/favicons?domain=intropic.io&sz=256' },
  { company: 'KPMG', title: 'Graduate Technology - Technology Consulting Glasgow Autumn 2026', type: 'Technology Consulting Graduate Scheme', location: 'Glasgow', deadline: 'Rolling', startDate: 'Autumn 2026', applyUrl: 'https://www.kpmgcareers.co.uk/Vacancies/graduatetechnologytechnologyconsultingglasgowautumn2026/95f3d8b1-5629-ec22-ad7d-a592f61ba5b5', website: 'https://www.kpmgcareers.co.uk', logo: 'https://www.google.com/s2/favicons?domain=kpmg.com&sz=256' },
  { company: 'KPMG', title: 'Graduate Technology - Technology Engineering Glasgow Autumn 2026', type: 'Technology Graduate Scheme', location: 'Glasgow', deadline: 'Rolling', startDate: 'Autumn 2026', applyUrl: 'https://www.kpmgcareers.co.uk/Vacancies/graduatetechnologytechnologyengineeringglasgowautumn2026/2d4b4c23-c6c2-f46d-a6e3-847424d4a190', website: 'https://www.kpmgcareers.co.uk', logo: 'https://www.google.com/s2/favicons?domain=kpmg.com&sz=256' },
  { company: 'Leonardo', title: 'Industrial Placement Software Engineer', type: 'Industrial Placement / Placement Year', location: 'Southampton', deadline: 'Rolling', startDate: 'Summer / Autumn 2026', applyUrl: 'https://careers.uk.leonardo.com/gb/en/job/R0022593/Industrial-Placement-Software-Engineer', website: 'https://uk.leonardo.com', logo: 'https://www.google.com/s2/favicons?domain=uk.leonardo.com&sz=256' },
  { company: 'M&G', title: 'Software Engineering Graduate', type: 'Software Engineering Graduate Scheme', location: 'United Kingdom', deadline: '14 September 2026', startDate: '14 September 2026', applyUrl: 'https://mgpru.wd3.myworkdayjobs.com/en-US/mandgprudential/job/Software-Engineering-Graduate_R18162', website: 'https://www.mandg.com', logo: 'https://www.google.com/s2/favicons?domain=mandg.com&sz=256' },
  { company: 'Marshall Wace', title: 'Technology Intern - London - Summer 2026', type: 'Technology Summer Internship', location: 'London', deadline: '29 June 2026', startDate: '29 June 2026', applyUrl: 'https://job-boards.greenhouse.io/mwinternshipprogram/jobs/7998360002', website: 'https://www.mwam.com', logo: 'https://www.google.com/s2/favicons?domain=mwam.com&sz=256' },
  { company: 'Mastercard', title: 'Software Engineer Intern, Summer 2026', type: 'Software Engineering Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://mastercard.wd1.myworkdayjobs.com/en-US/CorporateCareers/job/Software-Engineer-Intern--Summer-2026---London--UK_R-257373-2/apply/autofillWithResume', website: 'https://www.mastercard.co.uk', logo: 'https://www.google.com/s2/favicons?domain=mastercard.co.uk&sz=256' },
  { company: 'Mastercard', title: 'Technology Risk Analyst, Launch Graduate Program 2026', type: 'Technology Risk Graduate Programme', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://mastercard.wd1.myworkdayjobs.com/Campus/job/Technology-Risk-Analyst--Launch-Graduate-Program-2026---London--UK_R-256701/apply', website: 'https://www.mastercard.co.uk', logo: 'https://www.google.com/s2/favicons?domain=mastercard.co.uk&sz=256' },
  { company: 'Motorola Solutions', title: 'Graduate Software Engineer', type: 'Software Engineering Graduate Scheme', location: 'United Kingdom', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://motorolasolutions.wd5.myworkdayjobs.com/en-US/Careers/job/Graduate-Software-Engineer_R62287', website: 'https://www.motorolasolutions.com', logo: 'https://www.google.com/s2/favicons?domain=motorolasolutions.com&sz=256' },
  { company: 'MUFG', title: '2026 MUFG UK Summer Internship Programme - Technology Innovation Management', type: 'Technology Summer Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers/job/London/XMLNAME-2026-MUFG-UK-Summer-Internship-Programme--Technology-Innovation-Management_10072523-WD-1/apply/useMyLastApplication', website: 'https://www.mufg.com', logo: 'https://www.google.com/s2/favicons?domain=mufg.com&sz=256' },
  { company: 'NatWest Group', title: 'Tech Insight Experience for Women - Engineering', type: 'Insight Programme', location: 'London; Edinburgh', deadline: '31 May 2026', startDate: '18 September 2026', applyUrl: 'https://jobs.natwestgroup.com/jobs/17568644-tech-insight-experience-for-women-engineering', website: 'https://www.natwestgroup.com', logo: 'https://www.google.com/s2/favicons?domain=natwestgroup.com&sz=256' },
  { company: 'Northslope Technologies', title: 'Forward Deployed Software Engineer, New Grad', type: 'Software Engineering New Grad Programme', location: 'London', deadline: 'Rolling', startDate: '2026 / 2027', applyUrl: 'https://jobs.ashbyhq.com/northslope-technologies/7ccd126f-b127-4526-87f1-57408919c30a/application', website: 'https://www.northslope.ai', logo: 'https://www.google.com/s2/favicons?domain=northslope.ai&sz=256' },
  { company: 'Palantir', title: 'Forward Deployed Software Engineer, New Grad - UK Government', type: 'Software Engineering New Grad Programme', location: 'London', deadline: 'Rolling', startDate: '2026 / 2027', applyUrl: 'https://jobs.lever.co/palantir/b4aa51a2-bc43-4d67-bf55-12db7feefb3a/apply', website: 'https://www.palantir.com', logo: 'https://www.google.com/s2/favicons?domain=palantir.com&sz=256' },
  { company: 'Palantir', title: 'Product Designer, New Grad', type: 'Product Design New Grad Programme', location: 'London', deadline: 'Rolling', startDate: '2026 / 2027', applyUrl: 'https://jobs.lever.co/palantir/76161763-bafa-4ebb-a2ce-2a25e315b7d7/apply', website: 'https://www.palantir.com', logo: 'https://www.google.com/s2/favicons?domain=palantir.com&sz=256' },
  { company: 'Pear VC', title: 'Software Engineering Intern', type: 'Software Engineering Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://jobs.ashbyhq.com/Pear-VC/781a43c0-a13a-4e27-95a8-0dde6279d33f', website: 'https://www.pear.vc', logo: 'https://www.google.com/s2/favicons?domain=pear.vc&sz=256' },
  { company: 'Perplexity', title: 'UK Internship Program', type: 'Data/AI/ML Internship', location: 'United Kingdom', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://jobs.ashbyhq.com/perplexity/79a07e2d-6150-4929-80fe-bbe13a641763', website: 'https://www.perplexity.ai', logo: 'https://www.google.com/s2/favicons?domain=perplexity.ai&sz=256' },
  { company: 'Pfizer', title: 'AI Application Developer Undergraduate', type: 'AI / Software Industrial Placement', location: 'Walton Oaks', deadline: 'Rolling', startDate: '1 September 2026', applyUrl: 'https://pfizer.wd1.myworkdayjobs.com/en-US/pfizercareers/job/United-Kingdom---Walton-Oaks/AI-Application-Developer-Undergraduate_4956412', website: 'https://www.pfizer.co.uk', logo: 'https://www.google.com/s2/favicons?domain=pfizer.co.uk&sz=256' },
  { company: 'Procter & Gamble', title: 'Software Development Industrial Placement 2026', type: 'Software Development Industrial Placement', location: 'United Kingdom', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://pg.wd5.myworkdayjobs.com/en-GB/1000/job/Software-Development-Industrial-Placement-2026_R000147514/apply', website: 'https://www.pg.co.uk', logo: 'https://www.google.com/s2/favicons?domain=pg.co.uk&sz=256' },
  { company: 'PTC', title: 'Software Engineer Intern', type: 'Software Engineering Internship', location: 'Cambridge', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://ptc.wd1.myworkdayjobs.com/ptc/job/Cambridge-United-Kingdom/Software-Engineer-Intern_JR112226', website: 'https://www.ptc.com', logo: 'https://www.google.com/s2/favicons?domain=ptc.com&sz=256' },
  { company: 'Quantinuum', title: 'Internship Opportunities with Quantinuum 2026 - UK/Germany', type: 'Quantum Software / Cyber / ML Internship Talent Pool', location: 'London; Cambridge', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://jobs.eu.lever.co/quantinuum/dc2f6f9e-b409-4640-807d-0339a12dc3cd', website: 'https://www.quantinuum.com', logo: 'https://www.google.com/s2/favicons?domain=quantinuum.com&sz=256' },
  { company: 'Qube Research & Technologies', title: '2026 - Internship, Data Engineering', type: 'Data Engineering Internship', location: 'Paris; London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/quberesearchandtechnologies/jobs/8078338002', website: 'https://www.qube-rt.com', logo: 'https://www.google.com/s2/favicons?domain=qube-rt.com&sz=256' },
  { company: 'Qube Research & Technologies', title: '2026 - Internship, Machine Learning Engineer', type: 'Machine Learning Internship', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/quberesearchandtechnologies/jobs/8511818002', website: 'https://www.qube-rt.com', logo: 'https://www.google.com/s2/favicons?domain=qube-rt.com&sz=256' },
  { company: 'Qube Research & Technologies', title: '2026 - Internship, Quantitative Developer', type: 'Quant Developer Internship', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/quberesearchandtechnologies/jobs/8068131002', website: 'https://www.qube-rt.com', logo: 'https://www.google.com/s2/favicons?domain=qube-rt.com&sz=256' },
  { company: 'Qube Research & Technologies', title: '2026 - Internship, Quantitative Research/Trading', type: 'Quant / Trading Internship', location: 'London; Paris; Geneva; Zurich; Dubai; Aarhus; Budapest', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://job-boards.greenhouse.io/quberesearchandtechnologies/jobs/8052341002', website: 'https://www.qube-rt.com', logo: 'https://www.google.com/s2/favicons?domain=qube-rt.com&sz=256' },
  { company: 'Quilter', title: '8-week AI Graduate Internship', type: 'Data / AI / ML Graduate Internship', location: 'Southampton; London', deadline: 'Rolling', startDate: '8 June 2026', applyUrl: 'https://careers.quilter.com/early-careers/8-week-ai-graduate-internship/', website: 'https://www.quilter.com', logo: 'https://www.google.com/s2/favicons?domain=quilter.com&sz=256' },
  { company: 'Revolut', title: 'Graduate Programme 2027: Data Scientist and Analyst', type: 'Graduate Scheme', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'January-June 2027 or July-December 2027', applyUrl: 'https://www.revolut.com/careers/apply/fb71028e-634a-46bf-8be7-d85a3f929854/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Graduate Programme 2027: Product Designer', type: 'Graduate Scheme', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'January-June 2027 or July-December 2027', applyUrl: 'https://www.revolut.com/careers/apply/6487c60b-fff9-4519-aa1d-f5c6b26f7602/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Graduate Programme 2027: Product Owner (Technical)', type: 'Graduate Scheme', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'January-June 2027 or July-December 2027', applyUrl: 'https://www.revolut.com/careers/apply/554c4b14-c988-4c35-bd06-702acf4f36f7/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Graduate Programme 2027: Product Owner (UX)', type: 'Graduate Scheme', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'January-June 2027 or July-December 2027', applyUrl: 'https://www.revolut.com/careers/apply/48244271-6656-42f9-ab2c-caf4531593d3/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Graduate Programme 2027: Software Engineer (Android)', type: 'Software Engineering Graduate Programme', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'Early / Late 2027', applyUrl: 'https://www.revolut.com/careers/apply/dc268c11-5ef2-4398-8fe7-6e89dc8aebee/', website: 'https://www.revolut.com', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Graduate Programme 2027: Software Engineer (Frontend)', type: 'Graduate Scheme', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'January-June 2027 or July-December 2027', applyUrl: 'https://www.revolut.com/careers/apply/90f8f44d-d656-4c74-a6a5-a470b858179d/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Graduate Programme 2027: Software Engineer (iOS)', type: 'Software Engineering Graduate Programme', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'Early / Late 2027', applyUrl: 'https://www.revolut.com/careers/apply/726455bb-b707-4798-831d-253f7c8773de/', website: 'https://www.revolut.com', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Graduate Programme 2027: Software Engineer (Java)', type: 'Graduate Scheme', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'January-June 2027 or July-December 2027', applyUrl: 'https://www.revolut.com/careers/apply/3b79c804-b7e0-4b1a-9ef6-2fd69723dc7a/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Graduate Programme 2027: Software Engineer (Python)', type: 'Graduate Scheme', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'January-June 2027 or July-December 2027', applyUrl: 'https://www.revolut.com/careers/apply/f3f6861d-2013-4a52-b95f-15e44a73625f/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Graduate Programme 2027: Strategy & Operations Manager', type: 'Graduate Scheme', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'January-June 2027 or July-December 2027', applyUrl: 'https://www.revolut.com/careers/apply/f95a2dda-30a6-4fef-af87-db97199df832/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Internship Programme 2026: Product Designer', type: 'Summer Internship', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'June/July 2027', applyUrl: 'https://www.revolut.com/careers/apply/c2c28fdc-8cc9-4b3f-9e9b-126c723edb7a/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Internship Programme 2027: Data Scientist and Analyst', type: 'Summer Internship', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'June/July 2027', applyUrl: 'https://www.revolut.com/careers/apply/36855ffa-f704-40be-bf77-a8b4deb360fa/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Internship Programme 2027: Product Owner (Technical)', type: 'Summer Internship', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'June/July 2027', applyUrl: 'https://www.revolut.com/careers/apply/9bb26c86-9461-4e89-a460-7dc9a067b018/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Internship Programme 2027: Product Owner (UX)', type: 'Summer Internship', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'June/July 2027', applyUrl: 'https://www.revolut.com/careers/apply/d19156aa-506a-4cf5-bea2-2f4c999a1c41/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Internship Programme 2027: Software Engineer (Android)', type: 'Software Engineering Internship', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'June / July 2027', applyUrl: 'https://www.revolut.com/careers/apply/0e9d3624-2150-4802-b878-df63c6353606/', website: 'https://www.revolut.com', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Internship Programme 2027: Software Engineer (Frontend)', type: 'Summer Internship', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'June/July 2027', applyUrl: 'https://www.revolut.com/careers/apply/cb1769cb-4903-4525-982f-734217331544/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Internship Programme 2027: Software Engineer (iOS)', type: 'Software Engineering Internship', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'June / July 2027', applyUrl: 'https://www.revolut.com/careers/apply/bc2ddc16-c0ca-4c39-9db7-390db7f6cb3c/', website: 'https://www.revolut.com', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Internship Programme 2027: Software Engineer (Java)', type: 'Summer Internship', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'June/July 2027', applyUrl: 'https://www.revolut.com/careers/apply/a9cd5545-7d52-4e8f-bce9-1b67343ccc11/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Internship Programme 2027: Software Engineer (Python)', type: 'Summer Internship', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'June/July 2027', applyUrl: 'https://www.revolut.com/careers/apply/41b145ef-e5b7-4b87-9217-1ca8d5c5a0e5/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Revolut', title: 'Internship Programme 2027: Strategy & Operations Manager', type: 'Summer Internship', location: 'London; Remote UK', deadline: 'Rolling', startDate: 'June/July 2027', applyUrl: 'https://www.revolut.com/careers/apply/aa3cc201-5808-4d7e-ba8e-e82e443d90d3/', website: 'https://www.revolut.com/careers/', logo: 'https://www.google.com/s2/favicons?domain=revolut.com&sz=256' },
  { company: 'Rocket Lawyer', title: 'AI UX Conversational Analyst Intern', type: 'AI / UX Internship', location: 'London (Remote)', deadline: 'Rolling', startDate: '8 June 2026', applyUrl: 'https://job-boards.greenhouse.io/rocketlawyer/jobs/5183077008', website: 'https://www.rocketlawyer.com', logo: 'https://www.google.com/s2/favicons?domain=rocketlawyer.com&sz=256' },
  { company: 'Samsung AI Center Cambridge', title: 'Intern - AI Research', type: 'Data/AI/ML Internship', location: 'Cambridge', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://sec.wd3.myworkdayjobs.com/en-US/Samsung_Careers/job/Intern---AI-Research_R115071', website: 'https://research.samsung.com/aicenter_cambridge', logo: 'https://www.google.com/s2/favicons?domain=samsung.com&sz=256' },
  { company: 'Sierra', title: 'Intern, Agent Development (Fall 2026)', type: 'AI / Agent Software Engineering Internship', location: 'London', deadline: 'Rolling', startDate: 'Fall 2026', applyUrl: 'https://jobs.ashbyhq.com/Sierra/c74d600c-235c-4d42-8546-b178b7adefc2', website: 'https://www.sierra.ai', logo: 'https://www.google.com/s2/favicons?domain=sierra.ai&sz=256' },
  { company: 'Snap Inc.', title: 'Machine Learning Engineering Intern', type: 'Data/AI/ML Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://snapchat.wd1.myworkdayjobs.com/en-US/snap/job/Machine-Learning-Engineering-Intern_R0045123', website: 'https://www.snap.com', logo: 'https://www.google.com/s2/favicons?domain=snap.com&sz=256' },
  { company: 'SS&C Technologies', title: 'Machine Learning Intern, London', type: 'Data / AI / ML Internship', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://ssctech.wd1.myworkdayjobs.com/ssctechnologies/job/London---1-Ropemaker-Street/Machine-Learning-Intern--London_R42634/apply', website: 'https://www.ssctech.com', logo: 'https://www.google.com/s2/favicons?domain=ssctech.com&sz=256' },
  { company: 'SS&C Technologies', title: 'Quantitative Development Intern, London', type: 'Quant / Trading Technology Internship', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://ssctech.wd1.myworkdayjobs.com/SSCTechnologies/job/Quantitative-Development-Intern--London_R42635', website: 'https://www.ssctech.com', logo: 'https://www.google.com/s2/favicons?domain=ssctech.com&sz=256' },
  { company: 'SS&C Technologies', title: 'Summer Intern Systems Development', type: 'Software / Systems Development Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://ssctech.wd1.myworkdayjobs.com/ssctechnologies/job/London---1-Ropemaker-Street/Summer-Intern-Systems-Development_R43013-1/apply', website: 'https://www.ssctech.com', logo: 'https://www.google.com/s2/favicons?domain=ssctech.com&sz=256' },
  { company: 'Thomson Reuters', title: 'PhD Research Scientist Intern - Foundational Research', type: 'Data/AI/ML Internship', location: 'London', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://thomsonreuters.wd5.myworkdayjobs.com/en-US/External_Career_Site/job/Research-Scientist-Intern_JREQ198484', website: 'https://www.thomsonreuters.com', logo: 'https://www.google.com/s2/favicons?domain=thomsonreuters.com&sz=256' },
  { company: 'tldraw', title: 'R&D Intern', type: 'Software Engineering Internship', location: 'London', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://jobs.ashbyhq.com/tldraw/9f3f48d7-d731-4379-89f8-d4ee79ed5cfd', website: 'https://www.tldraw.com', logo: 'https://www.google.com/s2/favicons?domain=tldraw.com&sz=256' },
  { company: 'TPP', title: 'Graduate Software Developer', type: 'Software Engineering Graduate Scheme', location: 'Leeds', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://tpp-careers.com/roles/graduate-software-developer/', website: 'https://tpp-careers.com', logo: 'https://www.google.com/s2/favicons?domain=tpp-careers.com&sz=256' },
  { company: 'TPP', title: 'Graduate Technical Engineer', type: 'Technical Engineering Graduate Scheme', location: 'Leeds', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://tpp-careers.com/roles/graduatetechnicalengineer/', website: 'https://tpp-careers.com', logo: 'https://www.google.com/s2/favicons?domain=tpp-careers.com&sz=256' },
  { company: 'TPP', title: 'Summer Internship - Software Developer', type: 'Software Development Summer Internship', location: 'Leeds', deadline: 'Rolling', startDate: 'Summer 2026', applyUrl: 'https://tpp-careers.com/roles/summer-internship-software-developer/', website: 'https://tpp-careers.com', logo: 'https://www.google.com/s2/favicons?domain=tpp-careers.com&sz=256' },
  { company: 'UK Infrastructure Bank', title: 'IT Intern', type: 'Technology Internship', location: 'Leeds', deadline: 'Rolling', startDate: 'Summer/Autumn 2026', applyUrl: 'https://ukib.wd3.myworkdayjobs.com/en-US/UKIB/job/Leeds-HQ/IT-Intern_JR100387', website: 'https://www.ukib.org.uk', logo: 'https://www.google.com/s2/favicons?domain=ukib.org.uk&sz=256' },
  { company: 'Ultra', title: 'Graduate Software Engineer', type: 'Software Engineering Graduate Scheme', location: 'United Kingdom', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://ultra.wd3.myworkdayjobs.com/en-US/ultra-careers/job/Graduate-Software-Engineer_REQ-11210-2', website: 'https://www.ultra.group', logo: 'https://www.google.com/s2/favicons?domain=ultra.group&sz=256' },
  { company: 'Unisys', title: 'Projects Technical Support Intern (Placement Year, 2026 - 2027)', type: 'Technical Support / Infrastructure Placement Year', location: 'Manchester', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://unisys.wd5.myworkdayjobs.com/en-US/External/job/Manchester-United-Kingdom/Projects-Technical-Support-Intern--Placement-Year--2026---2027-_REQ571527/apply/autofillWithResume', website: 'https://www.unisys.com', logo: 'https://www.google.com/s2/favicons?domain=unisys.com&sz=256' },
  { company: 'Visa', title: 'Data Engineering Graduate', type: 'Data Engineering Graduate Scheme', location: 'United Kingdom', deadline: 'Rolling', startDate: 'October 2026', applyUrl: 'https://visa.wd5.myworkdayjobs.com/en-US/Visa_Early_Careers/job/Data-Engineering-Graduate_REF97107Z-1', website: 'https://www.visa.co.uk', logo: 'https://www.google.com/s2/favicons?domain=visa.co.uk&sz=256' },
  { company: 'Visa', title: 'Data Science Graduate', type: 'Data Science Graduate Scheme', location: 'United Kingdom', deadline: '6 October 2026', startDate: '6 October 2026', applyUrl: 'https://visa.wd5.myworkdayjobs.com/en-US/Visa_Early_Careers/job/Data-Science-Graduate_REF93870J', website: 'https://www.visa.co.uk', logo: 'https://www.google.com/s2/favicons?domain=visa.co.uk&sz=256' },
  { company: 'Visa', title: 'Software Engineering Higher (Level 4) Apprenticeship', type: 'Software Engineering Apprenticeship', location: 'Reading', deadline: 'Rolling', startDate: '2026', applyUrl: 'https://visa.wd5.myworkdayjobs.com/en-US/Visa_Early_Careers/job/Software-Engineering-Higher--Level-4--Apprenticeship_REF97167S', website: 'https://www.visa.co.uk', logo: 'https://www.google.com/s2/favicons?domain=visa.co.uk&sz=256' },
]

async function main() {
  console.log(`Seeding ${rows.length} opportunities from CSV…\n`)

  const usedSlugs: Record<string, boolean> = {}
  const existing = await prisma.opportunity.findMany({ select: { slug: true } })
  existing.forEach(o => { usedSlugs[o.slug] = true })

  const today = new Date('2026-05-30')

  let created = 0
  let skipped = 0

  for (const row of rows) {
    const companySlug = toSlug(row.company)

    // Upsert company with logo and website
    const comp = await prisma.company.upsert({
      where: { slug: companySlug },
      update: { website: row.website, logo: row.logo },
      create: { name: row.company, slug: companySlug, website: row.website, logo: row.logo },
    })

    // Generate unique slug
    const baseSlug = toSlug(`${row.company}-${row.title}`)
    let oppSlug = baseSlug
    let n = 2
    while (usedSlugs[oppSlug]) oppSlug = `${baseSlug}-${n++}`
    usedSlugs[oppSlug] = true

    const type = mapType(row.type)
    const deadline = parseDeadline(row.deadline)
    const status = !deadline ? 'OPEN' :
      deadline < today ? 'CLOSED' :
      deadline <= new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000) ? 'CLOSING_SOON' : 'OPEN'

    const workMode = mapWorkMode(row.location)

    try {
      await prisma.opportunity.create({
        data: {
          title: row.title,
          slug: oppSlug,
          description: `${row.title} at ${row.company}. Based in ${row.location}.`,
          type,
          location: row.location,
          workMode,
          deadline,
          startDate: row.startDate || undefined,
          sponsored: false,
          status: status as any,
          applyUrl: row.applyUrl || undefined,
          companyId: comp.id,
        },
      })
      console.log(`✓ [${type}] ${row.company} — ${row.title}`)
      created++
    } catch (e: any) {
      if (e.code === 'P2002') {
        console.log(`  (skip duplicate) ${row.company} — ${row.title}`)
        skipped++
      } else {
        console.error(`✗ ${row.company} — ${row.title}: ${e.message}`)
        skipped++
      }
    }
  }

  console.log(`\nDone! Created: ${created}, Skipped: ${skipped}`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
